name: base
channels:
  - defaults
  - bioconda
  - daler
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=4.3.0
  - archspec=0.2.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - attrs=23.2.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - comm=0.2.2
  - conda=24.3.0
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=23.12.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=41.0.7
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distro=1.8.0
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fmt=9.1.0
  - fqdn=1.5.1
  - icu=73.1
  - idna=3.4
  - importlib_resources=6.4.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - ipython_genutils=0.2.0
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - jsonpatch=1.32
  - jsonpointer=2.1
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter_client=7.4.9
  - jupyter_contrib_core=0.4.0
  - jupyter_contrib_nbextensions=0.7.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.6.1
  - jupyter_server=2.13.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab_pygments=0.3.0
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libarchive=3.6.2
  - libcurl=8.5.0
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libmamba=1.5.6
  - libmambapy=1.5.6
  - libnghttp2=1.57.0
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libssh2=1.10.0
  - libstdcxx-ng=13.2.0
  - libuuid=1.41.5
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lxml=4.9.2
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.6
  - menuinst=2.0.1
  - mistune=3.0.2
  - nbclassic=1.0.0
  - nbclient=0.10.0
  - nbconvert=7.16.3
  - nbconvert-core=7.16.3
  - nbconvert-pandoc=7.16.3
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=6.5.6
  - notebook-shim=0.2.4
  - openssl=3.2.1
  - overrides=7.7.0
  - packaging=23.1
  - pandoc=3.1.13
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.17.2
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.7
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python_abi=3.11
  - pyyaml=6.0.1
  - pyzmq=24.0.1
  - readline=8.2
  - referencing=0.34.0
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.18.0
  - ruamel.yaml=0.17.21
  - send2trash=1.8.3
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.6.2
  - terminado=0.18.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tornado=6.4
  - tqdm=4.65.0
  - traitlets=5.14.2
  - truststore=0.8.0
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_utils=0.1.0
  - tzdata=2023d
  - uri-template=1.3.0
  - urllib3=1.26.18
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
