name: mgr
channels:
  - defaults
  - bioconda
  - daler
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - biopython=1.78
  - blas=1.0
  - blast=2.15.0
  - bowtie2=2.5.3
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - clustalw=2.1
  - curl=8.5.0
  - dbus=1.13.18
  - entrez-direct=21.6
  - expat=2.5.0
  - fastqc=0.12.1
  - font-ttf-dejavu-sans-mono=2.37
  - fontconfig=2.12.1
  - freetype=2.7
  - glib=2.78.4
  - glib-tools=2.78.4
  - icu=73.2
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libcurl=8.5.0
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=13.2.0
  - libhwloc=2.10.0
  - libiconv=1.17
  - libidn2=2.3.4
  - libnghttp2=1.57.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsqlite=3.45.2
  - libssh2=1.10.0
  - libstdcxx-ng=13.2.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libxcb=1.15
  - libxml2=2.12.6
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - ncbi-vdb=3.1.0
  - ncurses=6.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjdk=11.0.13
  - openssl=3.0.13
  - pcre=8.45
  - pcre2=10.42
  - perl=5.32.1
  - perl-archive-tar=2.40
  - perl-carp=1.38
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.105
  - perl-encode=3.19
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-io-compress=2.201
  - perl-io-zlib=1.14
  - perl-json=4.10
  - perl-json-xs=2.34
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.62
  - perl-types-serialiser=1.01
  - pip=23.3.1
  - python=3.10.14
  - python_abi=3.10
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tbb=2021.12.0
  - tk=8.6.12
  - tzdata=2024a
  - viennarna=2.6.4
  - wget=1.21.4
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
